Algoritmo "Questao8"
// Fazer um algoritmo que receba o preço de custo de um produto e mostre como resposta o valor de venda. Sabese que o preço de custo receberá um acréscimo de acordo com um percentual informado pelo usuár
Var

a: inteiro
b: inteiro
c: real

Inicio

escreva("Insira o preço de custo de um produto: ")
leia(a)
escreva("Insira o percentual de acréscimo: ")
leia(b)

c <- b / 100

escreva("O valor de venda do seu produto será de R$", (a * c) + a)

Fimalgoritmo