Algoritmo "Questao1"
// Fazer um algoritmo que leia o numerador e o denominador de uma fração, e informe como resposta o
// número decimal correspondente a esta fração.
Var

num, den, dec: real


Inicio

escreval ("Insira o numerador de uma fração: ")
leia ( num )

escreval ("Agora, o denominador: ")
leia ( den )

dec <-  num / den

escreval ( "O número decimal correspondente à essa fração é: ", dec)


Fimalgoritmo